### ISSUE TITLE
Feature Request: remove stars

### ISSUE THREAD

**Issue by jradavenport** [barentsen/AstroGoldStars#4]
Could people tweet this?

```
@astrogoldstars I am very disappointed in @jradavenport--
```

And remove a star? Even rack up _negative_ stars?

**Comment by barentsen** [comment]
We discussed this at #dotastro and decided not to support this.

AstroGoldStars aims to solve the problem that small acts of kindness are missing from the community (as opposed to industry, e.g. Google or Microsoft, where employees can give each other positive points).

We don't need to support a way to enable small acts of un-kindness, there's enough of that already! =)
